
# Chat Analyzer Pro - Streamlit Configuration
# Place this file in: .streamlit/config.toml

[theme]
# Primary theme color (purple gradient)
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
# Server configuration
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200  # MB

# File watcher (for development)
fileWatcherType = "auto"

# WebSocket configuration
enableWebsocketCompression = true

[browser]
# Browser configuration
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[runner]
# Runner configuration
magicEnabled = true
fastReruns = true

[client]
# Client configuration
showErrorDetails = true
toolbarMode = "auto"

[logger]
# Logging configuration
level = "info"
messageFormat = "%(asctime)s - %(levelname)s - %(message)s"

[deprecation]
# Deprecation warnings
showPyplotGlobalUse = false

[mapbox]
# Mapbox token (if using maps)
# token = "your_mapbox_token_here"
